### ISSUE TITLE
this mesege is poping up an this has crash report

### ISSUE THREAD

**Issue by CrazyOwen01** [gryttr/KAGIC#13]
becuse i have a mod there is a crash report but it did not crash ---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2019-10-12 08:59:11 CDT
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at com.rhodojoel.brise.misc.SchematicLoader.findExit(SchematicLoader.java:126)
    at com.rhodojoel.brise.blocks.BlockGemDoorEnter.onBlockActivated(BlockGemDoorEnter.java:64)
    at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:449)
    at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 5 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2098494296 bytes (2001 MB) / 3959422976 bytes (3776 MB) up to 4294967296 bytes (4096 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
  FML: MCP 9.42 Powered by Forge 14.23.5.2846 Optifine OptiFine_1.12.2_HD_U_E3 73 mods loaded, 71 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                    | Version           | Source                                           | Signature                                |
       |:------ |:--------------------- |:----------------- |:------------------------------------------------ |:---------------------------------------- |
       | LCHIJA | minecraft             | 1.12.2            | minecraft.jar                                    | None                                     |
       | LCHIJA | mcp                   | 9.42              | minecraft.jar                                    | None                                     |
       | LCHIJA | FML                   | 8.0.99.99         | forge-1.12.2-14.23.5.2846.jar                    | None                                     |
       | LCHIJA | forge                 | 14.23.5.2846      | forge-1.12.2-14.23.5.2846.jar                    | None                                     |
       | LCHIJA | micdoodlecore         |                   | minecraft.jar                                    | None                                     |
       | LCHIJA | foamfixcore           | 7.7.4             | minecraft.jar                                    | None                                     |
       | LCHIJA | securitycraft         | v1.8.12           | [1.12.2]+SecurityCraft+v1.8.12.jar               | None                                     |
       | LCHIJA | damageindicatorsmod   | 1.0               | [1.12.2]DamageIndicatorsMod-3.4.9.jar            | None                                     |
       | LCHIJA | kagic                 | X11p13            | kagic-X11p13.jar                                 | None                                     |
       | LCHIJA | amalgam               | 1.0               | amalgam-1.0n11.jar                               | None                                     |
       | LCHIJA | thedragonlib          | 1.12.2-5.3.0      | thedragonlib-1.12.2-5.3.0.jar                    | None                                     |
       | LCHIJA | armorplus             | 1.12.2-11.24.0.60 | armorplus-1.12.2-11.24.0.60.jar                  | None                                     |
       | LCHIJA | jei                   | 4.13.1.225        | jei_1.12.2-4.13.1.225.jar                        | None                                     |
       | LCHIJA | quark                 | r1.6-177          | Quark-r1.6-177.jar                               | None                                     |
       | LCHIJA | autoreglib            | 1.3-32            | AutoRegLib-1.3-32.jar                            | None                                     |
       | LCHIJA | baubles               | 1.5.2             | Baubles-1.12-1.5.2.jar                           | None                                     |
       | LCHIJA | bedrockminer          | 1.0.5             | BedrockMiner-1.12.2-(v.1.0.5).jar                | None                                     |
       | LCHIJA | blocklings            | 6.0.1             | Blocklings+6.0.1+-+1.12.2.jar                    | None                                     |
       | LCHIJA | brise                 | @version          | brise-1.1_PATCH-1.jar                            | None                                     |
       | LCHIJA | carryon               | 1.12.1            | CarryOn+MC1.12.2+v1.12.1.jar                     | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
       | LCHIJA | ctm                   | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar                        | None                                     |
       | LCHIJA | chisel                | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar                     | None                                     |
       | LCHIJA | chiselsandbits        | 14.33             | chiselsandbits-14.33.jar                         | None                                     |
       | LCHIJA | extendedrenderer      | v1.0              | coroutil-1.12.1-1.2.32.jar                       | None                                     |
       | LCHIJA | coroutil              | 1.12.1-1.2.32     | coroutil-1.12.1-1.2.32.jar                       | None                                     |
       | LCHIJA | configmod             | v1.0              | coroutil-1.12.1-1.2.32.jar                       | None                                     |
       | LCHIJA | cosmeticarmorreworked | 1.12.2-v4a        | CosmeticArmorReworked-1.12.2-v4a.jar             | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCHIJA | creativeplus          | 1.0.2             | CreativePlus+MC1.12.2+v1.0.2.jar                 | None                                     |
       | LCHIJA | ctrades               | 1.3.3             | ctrades-1.3.3.jar                                | None                                     |
       | LCHIJA | customnpcs            | 1.12              | CustomNPCs_1.12.2(30Jan19).jar                   | None                                     |
       | LCHIJA | doggytalents          | 1.15.0.6          | DoggyTalents-1.12.2-1.15.0.6-universal.jar       | None                                     |
       | LCHIJA | llibrary              | 1.7.19            | llibrary-1.7.19-1.12.2.jar                       | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | dragonmounts          | 1.12.2-1.5.8      | DragonMounts-1.12.2-1.5.8(HOTFIX).jar            | None                                     |
       | LCHIJA | galacticraftcore      | 4.0.2.236         | GalacticraftCore-1.12.2-4.0.2.236.jar            | None                                     |
       | LCHIJA | galacticraftplanets   | 4.0.2.236         | Galacticraft-Planets-1.12.2-4.0.2.236.jar        | None                                     |
       | LCHIJA | mjrlegendslib         | 1.12.2-1.1.8      | MJRLegendsLib-1.12.2-1.1.8 (1).jar               | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCHIJA | extraplanets          | 1.12.2-0.5.6      | ExtraPlanets-1.12.2-0.5.6.jar                    | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCHIJA | foamfix               | 0.10.5-1.12.2     | foamfix-0.10.5-1.12.2.jar                        | None                                     |
       | LCHIJA | forgelin              | 1.8.3             | Forgelin-1.8.3.jar                               | None                                     |
       | LCHIJA | cfm                   | 6.3.0             | furniture-6.3.0-1.12.2 (1).jar                   | None                                     |
       | LCHIJA | futureminecraf        | 1.2.1.1           | FutureVersionsV1.2.1.1.jar                       | None                                     |
       | LCHIJA | ironman               | Beta-1.12.2-1.2.6 | IronMan-1.12.2-Beta-1.12.2-1.2.6.jar             | None                                     |
       | LCHIJA | speedsterheroes       | 1.12.2-2.1.4      | SpeedsterHeroes-1.12.2-2.1.4.jar                 | None                                     |
       | LCHIJA | lucraftcore           | 1.12.2-2.4.7      | LucraftCore-1.12.2-2.4.7.jar                     | None                                     |
       | LCHIJA | heroesexpansion       | 1.12.2-1.3.5      | HeroesExpansion-1.12.2-1.3.5.jar                 | None                                     |
       | LCHIJA | librarianlib          | 4.19.2            | librarianlib-1.12.2-4.19.2-release.jar           | None                                     |
       | LCHIJA | hooked                | %VERSION%         | hooked-1.0.3.jar                                 | None                                     |
       | LCHIJA | iceandfire            | 1.7.1             | iceandfire-1.7.1-1.12.2.jar                      | None                                     |
       | LCHIJA | infinity              | 1.10              | infinity-1.10.jar                                | None                                     |
       | LCHIJA | lucky                 | 7.6.0             | luckyblock-1.12.2-7.6.0.jar                      | None                                     |
       | LCHIJA | mclib                 | 1.0.2             | mclib-1.0.2-1.12.2.jar                           | None                                     |
       | LCHIJA | mcmultipart           | 2.5.3             | MCMultiPart-2.5.3.jar                            | None                                     |
       | LCHIJA | mekanism              | 1.12.2-9.7.8.379  | Mekanism-1.12.2-9.7.8.379 (1).jar                | None                                     |
       | LCHIJA | metamorph             | 1.1.8             | metamorph-1.1.8-1.12.2.jar                       | None                                     |
       | LCHIJA | mcef                  | 0.9               | Minecraft-Chromium-Embedded-Framework-1.12.2.jar | None                                     |
       | LCHIJA | obsidiantools         | 1.8.2             | ObsidianTools-1.8.2.jar                          | None                                     |
       | LCHIJA | overpoweredarmorbar   | @VERSION@         | overloadedarmorbar-1.0.4g.jar                    | None                                     |
       | LCHIJA | subcommonlib          | 1.2.0.1           | subcommonlib-sublib-1.12.2-1.2.0.4.jar           | None                                     |
       | LCHIJA | petbuddy              | $version          | petbuddy-petbuddy-1.12.2-2.4.1.0.jar             | None                                     |
       | LCHIJA | ptrmodellib           | 1.0.4             | PTRLib-1.0.4.jar                                 | None                                     |
       | LCHIJA | pymtech               | 1.12.2-1.0.2      | PymTech-1.12.2-1.0.2.jar                         | None                                     |
       | LCHIJA | the-fifth-world       | 0.5               | the-fifth-world-0.5.jar                          | None                                     |
       | LCHIJA | travellersbackpack    | 1.0.19.19         | TravellersBackpack-1.12.2-1.0.19.19.jar          | None                                     |
       | LCHIJA | ultimate_unicorn_mod  | 1.5.16            | ultimate_unicorn_mod-1.12.2-1.5.16.jar           | None                                     |
       | LCHIJA | vanillafix            | 1.0.10-SNAPSHOT   | VanillaFix-1.0.10-99.jar                         | None                                     |
       | LCHIJA | weather2              | 1.12.1-2.6.12     | weather2-1.12.1-2.6.12.jar                       | None                                     |
       | LCHIJA | webdisplays           | 1.0               | Web-Displays-Mod-1.12.2.jar                      | None                                     |
       | LCHIJA | wings                 | 1.1.5             | wings-1.1.5-1.12.2.jar                           | None                                     |
       | LCHIJA | bauble_wings          | 1.0.0             | wings-1.1.5-1.12.2.jar                           | None                                     |
       | LCHIJA | zombie_players        | 1.12.1-1.2.7      | zombie_players-1.12.1-1.2.7.jar                  | None                                     |
       | LCHIJA | librarianliblate      | 4.19.2            | librarianlib-1.12.2-4.19.2-release.jar           | None                                     |
       | UD     | mclib_core            | 1.0.2             | minecraft.jar                                    | None                                     |
       | UD     | mobends_wings         | 1.0.0             | wings-1.1.5-1.12.2.jar                           | None                                     |
  Loaded coremods (and transformers): wings (wings-1.1.5-1.12.2.jar)
                                        me.paulf.wings.server.asm.WingsRuntimePatcher
                                        me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.236.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      Quark Plugin (Quark-r1.6-177.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
                                        net.montoyo.mcef.coremod.ShutdownPatcher
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      ForgelinPlugin (Forgelin-1.8.3.jar)
                                        
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      McLib core mod (mclib-1.0.2-1.12.2.jar)
                                        mchorse.mclib.core.McLibCMClassTransformer
                                      LibrarianLib Plugin (librarianlib-1.12.2-4.19.2-release.jar)
                                        com.teamwizardry.librarianlib.asm.LibLibTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.7.jar)
                                        lucraft.mods.lucraftcore.core.LCTransformer
                                      pymtech (PymTech-1.12.2-1.0.2.jar)
                                        lucraft.mods.pymtech.core.PymTechClassTransformer
                                      MekanismCoremod (Mekanism-1.12.2-9.7.8.379 (1).jar)
                                        mekanism.coremod.KeybindingMigrationHelper
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Suspected Mods: KAGIC: Brisé (brise)

**Comment by Akrivus** [comment]
Please verify this is caused solely by KAGIC by removing Brise and attempting to replicate the issue. If the problem persists, please confer with official repository at: https://github.com/kagic/KAGIC

Otherwise, here is a link to Brise's Discord: https://discord.gg/AymGrJt
Thanks!
